### ISSUE TITLE
Video in main circle

### ISSUE THREAD

**Issue by blopker** [blopker/totem#102]
This ticket is to change the design and implement video in the main circle.

- How should we change the main circle screen to better support video?
- Modes
- - I'm speaking
- - Someone else is speaking
- - I'm receiving
- - I passed, but the next person hasn't received

I'm speaking
* Don't show self view, or keep it small
* Try to see everyone else
* Need a way to pass (Slide to pass? How does it work in browser/desktop)

Someone else is speaking
* Small/no self view
* Main focus is on the speaker
* Try to see everyone else as well, but smaller

**Comment by sebasnieb** [comment]
Feb 25 
Add the different possibilities for the video frames: when there are 2, or 4 or 10 etc.
For Open Open Floor functionality : add it to the functions
Add the Self-View function 
For mute on profile only show in active screen (tap) - think about having it less busy - maybe without the circle
Made options for when camera is disabled , like whether the pictured is blurred or the image is in black and white ... 
Add the bubble with the controls 
Not to explain engineers : Regarding the video view from the speakers perspective : the people I see in order are from 1st top left to last bottom right 
Name of the participants in the card : Set  the limit of characters for the names 
Work on the message of the "you will be next mock"
Include the mini video frames order at the bottom when is inactive screen .

**Comment by sebasnieb** [comment]
Hello Everyone 
So, 
✅ As a Speaker, I can see who is muted when the screen is active, and it disappears when its inactive:
https://www.figma.com/proto/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?page-id=0%3A1&node-id=934%3A14562&viewport=241%2C48%2C0.69&scaling=scale-down&starting-point-node-id=934%3A14562&show-proto-sidebar=1

✅ Added the "bubble" effect with the controls and actions at the bottom

✅ Different cases of layout depending on the number of connected users : 
12: https://www.figma.com/proto/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?page-id=0%3A1&node-id=934%3A14562&viewport=241%2C48%2C0.35&scaling=scale-down&starting-point-node-id=934%3A14562&show-proto-sidebar=1
11 participants https://www.figma.com/file/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?node-id=957%3A14955
10 to 9 : https://www.figma.com/file/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?node-id=966%3A14876
8 to 7: https://www.figma.com/proto/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?page-id=0%3A1&node-id=996%3A20474&viewport=241%2C48%2C0.69&scaling=scale-down&starting-point-node-id=996%3A20474&show-proto-sidebar=1
6 to 5 https://www.figma.com/proto/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?page-id=0%3A1&node-id=957%3A15391&viewport=241%2C48%2C0.69&scaling=scale-down&starting-point-node-id=957%3A15391&show-proto-sidebar=1
4 to 3:https://www.figma.com/proto/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?page-id=0%3A1&node-id=966%3A14753&viewport=241%2C48%2C0.69&scaling=scale-down&starting-point-node-id=966%3A15148&show-proto-sidebar=1
2 https://www.figma.com/proto/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?page-id=0%3A1&node-id=966%3A15230&viewport=241%2C48%2C0.69&scaling=scale-down&starting-point-node-id=966%3A15230&show-proto-sidebar=1

✅ Added open floor functionality and added the sub/menu of Keeper
 - while listening -- - ✔️  added also self-view button : https://www.figma.com/proto/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?page-id=0%3A1&node-id=985%3A17058&viewport=241%2C48%2C0.69&scaling=scale-down&starting-point-node-id=985%3A17058&show-proto-sidebar=1

 - while sharing: https://www.figma.com/proto/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?page-id=0%3A1&node-id=985%3A16746&viewport=241%2C48%2C0.69&scaling=scale-down&starting-point-node-id=972%3A15710&show-proto-sidebar=1

✅ Also added the selfview, for this while the other participants are moving video frames, mine is just a static image .
https://www.figma.com/file/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?node-id=986%3A17286

✅ keeping the mini video frames/turn order at the bottom when screen is inactive https://www.figma.com/proto/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?page-id=0%3A1&node-id=986%3A17286&viewport=241%2C48%2C0.69&scaling=scale-down&starting-point-node-id=986%3A17286&show-proto-sidebar=1

Note : 

For this version we didnt use icon for "Open Floor"  but would be worth dedicating more time to think about an appropriate graphical way of communicating this - would be good to to ask this in the interviews, what the keepers have "in mind" about an "Open Floor" 

Questions; should we include the mute icon in the mini-video frames? might be useful having it when the screen is active:
https://www.figma.com/file/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?node-id=1029%3A21524

Debating whether we use the close (X) icon for leaving or leave, as the log out icon reference : 
<img width="432" alt="Capture d’écran 2022-02-28 à 8 59 12 AM" src="https://user-images.githubusercontent.com/32967293/155945892-0a3d2747-4042-4e4b-9d07-762586d964e3.png">


-----------------------------------------------------------------------------------------------------------


Missing : 
Set limit of characters
How it looks the Self-View Action
How does the Open floor transition looks like 
VIdeo disabled layout
"You will be Next" message mock

**Comment by sebasnieb** [comment]
Hello, 
So I think that for setting up the number of characters I was thinking if it could be based on the text frame size, which could be maximized & Minimized depending on the size of the video box, so the text frame will be 8 px on each side from the X axis and from the Y axis 16 px, from bottom to top. This way when there is not enought space the text will end with "..." three dots at the end and when there is more space the text frame will be bigger and more content will be shown.
![margin](https://user-images.githubusercontent.com/32967293/156149661-3530ae67-475b-484b-b229-73ac81a9
<img width="1300" alt="Capture d’écran 2022-03-01 à 11 23 36 AM" src="https://user-images.githubusercontent.com/32967293/156151741-72191b08-7d8f-4985-ad10-c6a36aa8656e.png">
05d4.gif)

**Comment by sebasnieb** [comment]
No video Screen ideas:

1. https://www.figma.com/file/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?node-id=1046%3A16434
2. https://www.figma.com/proto/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?page-id=0%3A1&node-id=1047%3A16845&viewport=241%2C48%2C1.41&scaling=scale-down&starting-point-node-id=1047%3A16845&show-proto-sidebar=1

You are next Message 
https://www.figma.com/proto/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?page-id=0%3A1&node-id=1060%3A17801&viewport=241%2C48%2C1.41&scaling=scale-down&starting-point-node-id=0%3A192&show-proto-sidebar=1

Self-View action
For this the listener would have to keep pressed the button to see himself, as soon as released the frame dissapears - you can try here:
https://www.figma.com/proto/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?page-id=0%3A1&node-id=1066%3A16866&viewport=241%2C48%2C0.74&scaling=scale-down&starting-point-node-id=1066%3A16866&show-proto-sidebar=1

**Comment by sebasnieb** [comment]
March 4 Meeting 
- Open floor paused now 
- Self- view paused
- Icon for Leave (door) 
- - Open Floor Transition on Hold 
- No video Screen Idea for now : https://www.figma.com/file/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?node-id=1046%3A16434
- You are next message for second sprint 
-

**Comment by blopker** [comment]
@sebasnieb, the first iteration of this is done! Let's make another ticket for specific additional changes.
