### ISSUE TITLE
Anonymous browser circle join screen 

### ISSUE THREAD

**Issue by blopker** [blopker/totem#111]
This ticket is to design and develop the anonymous browser circle join screen.

This will allow a user to, after following a URL, to enter the name they want to use, see a preview image and to join the circle they were invited to.

This screen will also allow users to switch their audio and video inputs.

**Comment by sebasnieb** [comment]
Initial Ideal :  
https://www.figma.com/file/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?node-id=1249%3A19675
