### ISSUE TITLE
Desktop - tablet - mobile breaking points 

### ISSUE THREAD

**Issue by sebasnieb** [blopker/totem#118]
This ticket is to show the different breaking points between desktop - tablet - mobile landscape - mobile:

1. As Listener: https://www.figma.com/file/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?node-id=694%3A11492

2. To receive turn: https://www.figma.com/file/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?node-id=694%3A11492

3. As Speaker :   https://www.figma.com/file/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?node-id=694%3A11492

**Comment by blopker** [comment]
Done!
