### ISSUE TITLE
Website email capture

### ISSUE THREAD

**Issue by blopker** [blopker/totem#145]
This ticket is to improve the email capture on the website. The goal here is to build i high-quality email list for us to send out updates to, which will increase engagement in order to improve the number of people in circles metric.

The current email capture is not very good and does not have many (or any) signups.

Possible things to look into

- Design
- Copy
- What kind of content people are interested in
- The email people get when they submit their email

**Comment by zevastated** [comment]
Here’s my go at the email capture, still very much in progress. https://www.figma.com/file/qnpgINtlGRae3hFNOMG4B9/Totem-Affinity-Map?fuid=984621865127413429

**Comment by blopker** [comment]
https://emailmastery.org/teardown/the-headspace-email-marketing-teardown/

**Comment by zevastated** [comment]
Seb's design under "EMAIL"
https://www.figma.com/file/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app

**Comment by micahp2** [comment]
I've updated the wireframes based on the Q&A and feedback. The new links are...

Wireframes:
https://drive.google.com/file/d/1m9hY86meoXhMfmnSINz1c0Cr9crB5Fbr/view?usp=sharing

Feedback:
https://docs.google.com/document/d/1e6s0wwlQWZ8VZIe268oCQ1uhBBjfdLG7yWk7AoYUVtU/edit?usp=sharing
