### ISSUE TITLE
Handle Wi-Fi dropping more gracefully

### ISSUE THREAD

**Issue by blopker** [blopker/totem#150]
This ticket is to handle connection issues more gracefully. Right now an error pops up when WiFi drops. This ticket is to add a 30s timeout before any connection errors are thrown.

**Comment by sebasnieb** [comment]
@blopker should we prepare an illustration to show this error ? like a more engaging way of showing this?

**Comment by blopker** [comment]
Good ask. The scope of this ticket is to see what our recovery options look like before we need to show any errors, so not for this ticket. However, if you have an idea for a good generic error illustration we can certainly use that!
