### ISSUE TITLE
Better Hierarchy between who is talking and 

### ISSUE THREAD

**Issue by sebasnieb** [blopker/totem#165]
## Overview
As a listener, I need to know and understand who has more importance - know which screen I should focus more - the speaker - 
For this we should do the following:
1. Include a separation line between the main speaker and the rest
2. Maintain the same size of the other guests (including me) even if it is only one or two besides the speaker.

## Screenshot
DESKTOP
<img width="1310" alt="Capture d’écran 2022-05-15 à 12 01 47 PM" src="https://user-images.githubusercontent.com/32967293/168467273-153ce999-2de4-4bd0-999e-07107ae29d07.png">
1. Is the the separating line
2. size of the frame

MOBILE
<img width="750" alt="Capture d’écran 2022-05-15 à 12 20 42 PM" src="https://user-images.githubusercontent.com/32967293/168467965-bbf71b5a-51a9-42cf-be33-f11b5d930191.png">

TABLET
<img width="953" alt="Capture d’écran 2022-05-15 à 12 48 44 PM" src="https://user-images.githubusercontent.com/32967293/168469018-57574fed-6c31-4bde-8f2b-a4a162d10a9c.png">

## Description
1. For the line: Color #696B76, size 2 px .

For Desktop & Tablet
 the size of the line should cover the video of the speaker - from the main speaker to the line there are horizontally 32 px and 32 px from the line to the guests 
<img width="909" alt="Capture d’écran 2022-05-15 à 1 10 35 PM" src="https://user-images.githubusercontent.com/32967293/168469720-ebf63f85-4a70-4e43-9240-03b899c78d1a.png">

For mobile it should be across the screen horizontally, separating the speaker and the others
from the main speaker to the line there are vertically 16 px and 16 px from the line to the guests .
<img width="895" alt="Capture d’écran 2022-05-15 à 1 13 27 PM" src="https://user-images.githubusercontent.com/32967293/168469855-5c246c33-e0be-4b6b-b08a-82d3fd696379.png">

2. For the frame : 

Desktop & Tablet 
 
The frame should have : 3 frames next to each other in the same row with a separation between them of 8 px.

Mobile 
The frames shoud be 3 per row with a separtion of 3 to 4 px between each other

@blopker

**Comment by sebasnieb** [comment]
I was thinking to have it like that to avoid having too much spacing between both sections.
But wecan have something like this:
<img width="836" alt="Capture d’écran 2022-05-20 à 9 16 43 AM" src="https://user-images.githubusercontent.com/32967293/169474180-954ffee8-eaa5-4eca-a993-12df0672c8f1.png">

**Comment by blopker** [comment]
For now we're going to just do the divider line. @sebasnieb, we need to discuss a bit more in detail how the participant list should scale.
