### ISSUE TITLE
Home screen circle list obscured by create button

### ISSUE THREAD

**Issue by blopker** [blopker/totem#17]
On the home screen, if there are many circles available, the last circle is obscured by the Create Circle button. It seems like there needs to be padding or something added to the end of the circle list.

<img width="321" alt="image" src="https://user-images.githubusercontent.com/757503/140465222-7f4d8497-5485-4b8d-9b66-62c521b3e5ca.png">

**Comment by schalky** [comment]
should be addressed by the latest code merge

**Comment by blopker** [comment]
Checked, fixed! Thanks.
