### ISSUE TITLE
Change Microphone off icon

### ISSUE THREAD

**Issue by sebasnieb** [blopker/totem#182]
## Overview
At the moment when entering a circle, both in mobile and desktop, when I have my microphone off, we have the old version of the mic off, the black bubble with the icon.
Let's update it to the newer version.

## Screenshot
1.
<img width="1281" alt="Capture d’écran 2022-06-04 à 7 56 38 PM" src="https://user-images.githubusercontent.com/32967293/172019758-209e2ca1-9686-4352-beef-c02003718638.png">

## Description
Comparison of the current site VS Design
Design figma link [here](https://www.figma.com/file/Q8ZcLftDd8JQ9HIFz0DZJD/Totem-app?node-id=1920%3A26907)

@blopker

**Comment by blopker** [comment]
Great, thanks for this. Putting on deck.
