### ISSUE TITLE
Misc Edit Profile Changes

### ISSUE THREAD

**Issue by blopker** [blopker/totem#29]
<img width="564" alt="image1" src="https://user-images.githubusercontent.com/757503/146277026-ea6f0c2f-4770-47f1-aba5-4bb55379adab.png">

This ticket is a punch list for a few items to change on the Edit Profile screen.

1. Change "Done" to "Save". Functionally, nothing should be saved to the server until the "Save" button is pressed. I think this is the case now for everything except the profile image which is saved separately. The profile picture capture field changes will have its own ticket.
2. "?" and "X" buttons need bigger hit boxes. For the "?" buttons, they should be moved next to their label ("Name") and clicking the label should trigger the popup as well.
3. The "Sign Out" button is too easy to hit. This should be used rarely. Please make it just a centered text button with no icon and bring it down a few font sizes. Additionally do not have it floating. Instead, have it appended to the bottom of the form with generous padding. This will make it so it doesn't float around when the keyboard is activated.
4. Add the profile's phone number to the Edit Profile screen form after the email field, it should be read-only. This will help us know what account we are using and will also help users know what number they used to sign up.

**Comment by schalky** [comment]
resolved items as outlined. Also added version number to the bottom of the page below the sign out link.

**Comment by blopker** [comment]
Nice, I'll check it out tomorrow!
