### ISSUE TITLE
Audio not coming through speaker

### ISSUE THREAD

**Issue by blopker** [blopker/totem#38]
On Android, Pixel 6 and 5 the audio is not coming through the speaker and instead is coming through the earpiece, like a phone call. Ultimately we'd like the audio to come through the speaker if the person is holding the phone away from their ear and from the earpiece if they are holding it to their head.

**Comment by schalky** [comment]
@blopker I made a small change to set the default audio to hopefully route to speaker. This is in the 0.1.3 build that just came out. If you could try and see if it works, i don't have a device that fails similar to yours.

**Comment by blopker** [comment]
I did try 0.1.3 with @sebasnieb this morning and the issue was still there. Is there a newer build? Also, I was able to publish the Android release, but I'm curious what your workflow is.

Have you not been able to replicate the speaker issue on your side yet?
