### ISSUE TITLE
Sound turns off when phone goes to sleep

### ISSUE THREAD

**Issue by blopker** [blopker/totem#41]
This ticket is to make sure the audio doesn't disconnect when the phone isn't interacted with for a while. This is an issue on Android.

Possible fixes:
* Keep the screen on
* Put the audio in the background ala whatsapp or Spotify.

**Comment by schalky** [comment]
https://pub.dev/packages/android_long_task
this may be the answer for android

**Comment by schalky** [comment]
used a different package that had more control over the process of creating the service.
