### ISSUE TITLE
Skip and Open room functionalities

### ISSUE THREAD

**Issue by sebasnieb** [blopker/totem#99]
Currenlty in the app, as a keeper the skip and Open Room functionalities don't work .

**Comment by blopker** [comment]
Actually, can we remove the Open Room button for this ticket instead? Right now people can just unmute themselves if needed.

**Comment by sebasnieb** [comment]
Ahh Okay, 
So we will let them mte/unmute themselves ?
I thought this was at the beginning one of the many main issues, that people let their microphone on etc

**Comment by blopker** [comment]
This would only be the case if the Keeper wants people to speak out of turn, which should not happen a lot. Otherwise the mute/unmute issue is taken care of by the turn mechanic. We can always add this back later, but I'm thinking it's not worth putting in now since there's a workaround.

**Comment by sebasnieb** [comment]
Alrighty, makes sense.
Will remove it from the action menu for the mean time .

**Comment by sebasnieb** [comment]
BTW are we allowing people to turn off the camera?

**Comment by blopker** [comment]
For now, yes. I want to get more feedback from people though. I could imagine a "step away" button that turns off video, but also audio. The digital equivalent of leaving the room for a second.

**Comment by sebasnieb** [comment]
Oh nice, I like that!
Let's test it out first :)

**Comment by blopker** [comment]
Closing in favor of https://github.com/blopker/totem/issues/123
